### ISSUE TITLE
Can't use version 2.5 of Riot's League API in LeagueWrap

### ISSUE THREAD

**Issue by Jasonfran** [paquettg/leaguewrap#57] opened 2015-02-01 15:35 UTC
I have tried using selectVersion('v2.5'); like so:
![example](http://i.imgur.com/jsio4eF.png)
but this still uses v2.4 of the League API. And because v2.4 of the API no longer accepts requests I get a 401 response. You can see that it still uses 2.4 right here.
![Example](http://i.imgur.com/nZpXuO8.png)

The program ran flawlessly before they updated their API, I just need to use the League API but LeagueWrap insists on using v2.4

**I am running 0.6.0 because updating to 0.6.1 breaks the whole thing and throws Guzzle request exceptions for no reason**

![here](http://i.imgur.com/bKZ3w2i.png)

**Comment by danijoo** [comment] 2015-02-01 19:41
Thats really strange. It should use version 2.5 by default on 0.6.1 as well as 0.6.0 (and it does for me). Can you please show the code you are using to creating the api object and doing the request?

Im not sure about the error with guzzle. Maybe paquettg knows more about that. It works flawless for me.

**Comment by paquettg** [comment] 2015-02-02 14:59
It's strange that your being forced into 2.4 while the change to update the code to use 2.5 was added months ago (https://github.com/paquettg/leaguewrap/commit/7f6d72a049034f52b87062851f1dfa722641526d). 

Now, for the guzzle exception that is caused by updating to 0.6.1... here is the changes in between 0.6.0 and 0.6.1

https://github.com/paquettg/leaguewrap/compare/0.6.0...0.6.1

I can't tell any changes that would effect guzzle or the code that uses it but i'll keep looking to see if I can replicate the issues you are having, as strange as they are.

**Comment by Jasonfran** [comment] 2015-02-02 22:06
I'm not sure what is causing it, here is the code I am using that currently causes the problem. Sorry if it's bad code (it probably is by the looks of it) I'm pretty new to this, but it did work.

    <?php
	header('Access-Control-Allow-Origin: *');
	header('Content-Type: application/json');
	require 'vendor/autoload.php';

	use LeagueWrap\Api;

	$myKey = "XXXXXXXXXXXXXXXXXXXXXXXX";

	if (($_GET["region"] || $_GET["summoner"]) == NULL){
		exit('{"success":"false", "error":"No summoner name or region"}');
	}

	$region = $_GET["region"];
	$summonerName = $_GET["summoner"];

	$regions = ["BR", "EUNE", "EUW", "KR", "LAN", "LAS", "NA", "OCE", "RU", "TR"];

	if (!in_array($region, $regions)){
		exit('{"success":"false", "error":"Incorrect region"}');
	}

	$api = new Api($myKey); // Load up the API
	$api->remember(60);
	$api->setRegion($region);
	$summoner = $api->summoner();
	try{
		$summonerInfo = $summoner->info($summonerName);
		//print_r($summonerInfo);
	}catch(Exception $e){
		//print($e);
		exit('{"success":"false", "error":"Summoner not found in the system"}');
	}

	$summonerInfoArray = [
			"basicStats" => [
				"level" => $summonerInfo->summonerLevel,
				"name" => $summonerInfo->name,
				"profileIcon" => $summonerInfo->profileIconId
			]
		];

		// my summoner id 41217037

	try{
		$league =  $api->league();
		$league->selectVersion('v2.5');

		$summonerLeague = $league->league($summonerInfo->id, true);
		$summonerLeagueArray = [
		"rankedSummary" =>[
			"leagueName" => $summonerLeague[0]->name,
			"division" => $summonerLeague[0]->tier." ".$summonerLeague[0][0]->division,
			"LP" => $summonerLeague[0][0]->leaguePoints,
			"rankedWins" => $summonerLeague[0][0]->wins
			]
		];
	}catch(Exception $e){
		print($e); //This is what shows me the 401 unauthorised because it uses the old API
		$summonerLeagueArray = [
		"rankedSummary" => [
			"leagueName" => "Unranked",
			"division" => "Unranked",
			"LP" => "Unranked",
			"rankedWins" => "Unranked"
			]
		];
	}

**Comment by danijoo** [comment] 2015-02-03 13:56
I really cant explain this. First, you should not need this line: **$league->selectVersion('v2.5');**
The api sets the correct version automatically to the most up-to-date.
Can you please show your composer file too? A wrong version of leaguewrap that has 2.4 as default would be my guess.

**Comment by paquettg** [comment] 2015-02-16 16:27
I am closing this as it's been 2 weeks since we have heard anything on this topic. If you are still having a problem you can keep posting here and I'll re-open the issue.

**Closed by paquettg** 2015-02-16 16:27 UTC
Labels: bug

**Comment by Jasonfran** [comment] 2015-02-16 16:33
The issue is still there but I have no idea how to sort it.
